name: FordhamAR
description: Fordham AR is an augmented reality application that allows users to explore Fordham University's Rose Hill campus in a new and interactive way. Users can view 3D models of buildings, navigate through the campus, and learn more about the history of the university.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.8.0
  camera: ^0.11.0+2

  tflite: ^1.1.2
  flutter_markdown: ^0.7.3+1
  google_fonts: ^6.2.1
  arkit_plugin: ^1.1.0
  circular_menu: ^4.0.0
  google_maps_flutter: ^2.7.0
  flutter_polyline_points: ^2.0.0
  flutter_riverpod: ^2.5.1
  flutter_rating_stars: ^1.1.0
  flip_card: ^0.7.0
  flutter_carousel_widget: ^2.3.0
  cached_network_image: ^3.3.1
  xml2json: ^6.2.3
  dart_rss: ^3.0.1
  url_launcher: ^6.2.6
  dart_openai: ^5.1.0
  markdown_widget: ^2.3.2+3
  font_awesome_flutter: ^10.7.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.9
  english_words: ^4.0.0
  image_cropper: ^8.0.2
  loading_animation_widget: ^1.2.0+4
  flutter_lorem: ^2.0.0
  flutter_launcher_icons: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.0


flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icons/1024.png
  min_sdk_android: 21
  flutter_lints: ^3.0.0










# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
   - assets/images/
   - assets/images/backgrounds/
   - assets/detect_x1.tflite
   - assets/model_fdn.tflite
   - assets/detect2.tflite
   - assets/fnd_1.tflite
   - assets/model.tflite
   - assets/last-fp16.tflite
   - assets/fdn.txt
   - assets/yolov5n.tflite
   - assets/yolo5n.txt
   - assets/yolov2_tiny.tflite
   - assets/yolov2_tiny.txt
   - assets/ssd_mobilenet.tflite
   - assets/ssd_mobilenet.txt
   - assets/mobilenet_v1_1.0_224.tflite
   - assets/mobilenet_v1_1.0_224.txt
   - assets/posenet_mv1_075_float_from_checkpoints.tflite

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
