import 'package:google_maps_flutter/google_maps_flutter.dart';

final cardInfo = [
  {
    'image': 'assets/images/backgrounds/7.png',
    'name': 'Bathgate Hall',
    'location': LatLng(40.86011782614106, -73.88675769892497),
    'subText': 'Academic building at Fordham University.',
    'list1': 'Home to various academic departments and faculty offices.',
    'list2': 'Features state-of-the-art classrooms and computer labs.',
    'list3': 'Accessible for students during regular university hours.',
    'list4': 'Often used for lectures and student activities.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'Lorillard_.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Mulcahy - Keating',
    'location': LatLng(40.8602013, -73.8844390),
    'subText': 'Pathway between Mulcahy and Keating Halls.',
    'list1': 'Connects two major academic buildings.',
    'list2': 'A scenic route surrounded by campus greenery.',
    'list3': 'Commonly used by students between classes.',
    'list4': 'Leads to nearby parking and recreational facilities.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'mc_hall_2.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Keating Back',
    'location': LatLng(40.8601683, -73.8836578),
    'subText': 'Backside of Keating Hall.',
    'list1': 'Offers a quieter side entrance for easy access.',
    'list2': 'Frequently used by students and faculty.',
    'list3': 'Near the university’s historical architecture.',
    'list4': 'Leads to the main quad and Edward’s Parade.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'keating3.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'O’Hare Hall',
    'location': LatLng(40.8598103, -73.8824994),
    'subText': 'Residence hall for students.',
    'list1': 'Provides housing primarily for freshmen and sophomores.',
    'list2': 'Equipped with study lounges, laundry, and social spaces.',
    'list3': 'Located near the main campus dining facilities.',
    'list4': 'Has views overlooking nearby athletic fields.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'ohare_hall.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Moglia Stadium',
    'location': LatLng(40.8611839, -73.8837628),
    'subText': 'Home stadium for Fordham athletics.',
    'list1': 'Hosts football games and other athletic events.',
    'list2': 'Equipped with modern bleachers and press boxes.',
    'list3': 'Located next to the practice field and fitness center.',
    'list4': 'Frequently used by the university community for events.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'field_1.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Tennis Court',
    'location': LatLng(40.8633417, -73.8855467),
    'subText': 'Outdoor tennis courts for students and staff.',
    'list1': 'Accessible to students for recreational play.',
    'list2': 'Regularly used by the university tennis team.',
    'list3': 'Surrounded by greenery, offering a scenic setting.',
    'list4': 'Near athletic facilities, convenient for sports events.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'field_1.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Cemetery',
    'location': LatLng(40.8634756, -73.8858471),
    'subText': 'Historic cemetery on campus.',
    'list1': 'A quiet and reflective space on campus.',
    'list2': 'Preserves historical monuments and headstones.',
    'list3': 'Frequently visited during campus tours.',
    'list4': 'Surrounded by trees and gardens, adding to its tranquility.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'Street View 360_1.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Fordham Prep School',
    'location': LatLng(40.8640126, -73.8862444),
    'subText': 'Preparatory school associated with Fordham University.',
    'list1': 'One of the oldest high schools in New York.',
    'list2': 'Provides rigorous academic programs for young students.',
    'list3': 'Close partnership with Fordham University.',
    'list4': 'Offers facilities shared with university students.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'fordham_prep_school.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Loschert Hall',
    'location': LatLng(40.8638970, -73.8868402),
    'subText': 'Residence hall for students.',
    'list1': 'Provides housing for undergraduate students.',
    'list2': 'Equipped with study areas and social spaces.',
    'list3': 'Located near the main campus dining facilities.',
    'list4': 'Conveniently located close to academic buildings.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'loschert_hall.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'St. John and Tueds',
    'location': LatLng(40.8636748, -73.8866543),
    'subText': 'Intersection between two notable campus buildings.',
    'list1': 'Close to main lecture halls and student facilities.',
    'list2': 'Popular area for students to gather and study outdoors.',
    'list3': 'Has seating and shaded areas for relaxation.',
    'list4': 'Connected to other key campus pathways.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'st_john_tueds.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Church and Brownson',
    'location': LatLng(40.8632446, -73.8867571),
    'subText': 'Intersection near the campus church and Brownson Hall.',
    'list1': 'Close to the university chapel and religious center.',
    'list2': 'A peaceful spot surrounded by trees and benches.',
    'list3': 'Leads to both academic and residential areas.',
    'list4': 'Frequent site for student meetings and events.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'church_brownson.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Loyola Hall',
    'location': LatLng(40.8625944, -73.8858394),
    'subText': 'Residential building on campus.',
    'list1': 'One of the main residence halls for students.',
    'list2': 'Offers both single and double occupancy rooms.',
    'list3': 'Located near key campus facilities and dining.',
    'list4': 'Has study lounges and recreational spaces for residents.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'loyola_hall.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Waterfall',
    'location': LatLng(40.8617097, -73.8858097),
    'subText': 'Scenic waterfall located on campus.',
    'list1': 'A tranquil spot popular for relaxation and photography.',
    'list2': 'Surrounded by benches and green areas for a peaceful ambiance.',
    'list3': 'Often visited by students seeking a quiet study spot.',
    'list4': 'Located near major walking paths across campus.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'water_fall_1.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Cunniffe Hall',
    'location': LatLng(40.8619213, -73.8862813),
    'subText': 'Administrative center of the campus.',
    'list1': 'Houses key university offices and administrative services.',
    'list2': 'Home to the President’s office and student services.',
    'list3': 'Grand architectural design with an impressive interior.',
    'list4': 'Hosts several events and meetings throughout the year.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'cunniffe_hall.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Dealy Hall',
    'location': LatLng(40.8616210, -73.8864332),
    'subText': 'Main academic building on campus.',
    'list1': 'Hosts classes for various academic departments.',
    'list2': 'Equipped with lecture halls and modern technology.',
    'list3': 'Commonly used for seminars and special lectures.',
    'list4': 'Contains faculty offices and student resource centers.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'dealy_hall.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Duane Library',
    'location': LatLng(40.8614574, -73.8872238),
    'subText': 'Historic library on campus.',
    'list1': 'Offers a vast collection of academic resources.',
    'list2': 'Provides quiet study areas and computer labs.',
    'list3': 'Popular among students preparing for exams.',
    'list4': 'Features beautiful architecture and a reading room.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'duane_library.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Larkin Hall',
    'location': LatLng(40.8609952, -73.8882417),
    'subText': 'Residence hall for students.',
    'list1': 'Located near the main campus entrance.',
    'list2': 'Offers comfortable rooms and community spaces.',
    'list3': 'Houses undergraduate students primarily.',
    'list4': 'Equipped with a shared kitchen and laundry facilities.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'larkin_hall.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Library',
    'location': LatLng(40.86150607299467, -73.88896543957128),
    'subText': 'Central library for all academic research.',
    'list1': 'Large collection of books, journals, and digital resources.',
    'list2': 'Includes study rooms and collaborative spaces.',
    'list3': 'Open to students, faculty, and researchers.',
    'list4': 'Hosts research workshops and study groups.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'library.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Library',
    'location': LatLng(40.8613762230225, -73.88928727085484),
    'subText': 'Central library for all academic research.',
    'list1': 'Large collection of books, journals, and digital resources.',
    'list2': 'Includes study rooms and collaborative spaces.',
    'list3': 'Open to students, faculty, and researchers.',
    'list4': 'Hosts research workshops and study groups.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'library.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Library',
    'location': LatLng(40.861441129200436, -73.88841823075154),
    'subText': 'Central library for all academic research.',
    'list1': 'Large collection of books, journals, and digital resources.',
    'list2': 'Includes study rooms and collaborative spaces.',
    'list3': 'Open to students, faculty, and researchers.',
    'list4': 'Hosts research workshops and study groups.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'library.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Gate',
    'location': LatLng(40.861226150882246, -73.89011879668851),
    'subText': 'Main entrance gate of the campus.',
    'list1': 'Entry point for visitors and students alike.',
    'list2': 'Features the university logo and signage.',
    'list3': 'Serves as a meeting spot and information point.',
    'list4': 'Nearby security ensures campus safety.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'gate.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Campbell Hall',
    'location': LatLng(40.86236402896374, -73.88907875259216),
    'subText': 'Student residence hall.',
    'list1': 'Offers both single and shared room accommodations.',
    'list2': 'Has study lounges and recreational areas.',
    'list3': 'Conveniently located near dining facilities.',
    'list4': 'Equipped with high-speed internet and security systems.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'campbell_hall.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Salice Hall',
    'location': LatLng(40.86278368807378, -73.88868700273055),
    'subText': 'Student dormitory.',
    'list1': 'Provides comfortable living arrangements.',
    'list2': 'Features common areas and study spaces.',
    'list3': 'Located near other residence halls and amenities.',
    'list4': 'Regularly hosts residence life events for students.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'salice_hall.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Martyrs\' Court',
    'location': LatLng(40.862467046668414, -73.88849062920174),
    'subText': 'Residential complex for students.',
    'list1': 'Composed of multiple wings for different communities.',
    'list2': 'Includes lounges and meeting rooms.',
    'list3': 'Central location near academic and social buildings.',
    'list4': 'Offers a supportive environment for student residents.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'martyrs_court.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'McGinley Center',
    'location': LatLng(40.86266254185804, -73.8840971040944),
    'subText': 'Student center for activities and services.',
    'list1': 'Home to dining, student organizations, and retail.',
    'list2': 'Hosts events, clubs, and student government offices.',
    'list3': 'Popular gathering spot for students on campus.',
    'list4': 'Includes lounges, study areas, and meeting rooms.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'mcginley_center.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Jack Coffey Field',
    'location': LatLng(40.86147765821646, -73.88261187068268),
    'subText': 'Main athletic field for sports events.',
    'list1': 'Used for football, soccer, and other sports.',
    'list2': 'Hosts university games and tournaments.',
    'list3': 'Equipped with seating for spectators and scoreboards.',
    'list4': 'Surrounded by walking tracks and open spaces.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'jack_coffey_field.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Amazon Locker',
    'location': LatLng(40.86381962609719, -73.88730816541958),
    'subText': 'Convenient package pickup location on campus.',
    'list1': 'Provides secure package storage for students.',
    'list2': 'Accessible with Amazon pickup codes.',
    'list3': 'Located near major student pathways for convenience.',
    'list4': 'Ensures students can retrieve packages any time.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'amazon_locker.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Tennis Court',
    'location': LatLng(40.86393423956953, -73.8850119381504),
    'subText': 'Outdoor tennis courts for recreational use.',
    'list1': 'Available for both student and faculty use.',
    'list2': 'Well-maintained surfaces with lighting for evening play.',
    'list3': 'Hosts occasional tournaments and recreational games.',
    'list4': 'Located near other athletic facilities on campus.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'tennis_court.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Bahoshy Field',
    'location': LatLng(40.86334881121144, -73.88466008803972),
    'subText': 'Home of the university’s softball team.',
    'list1': 'Field for competitive and recreational softball games.',
    'list2': 'Equipped with dugouts, seating, and a scoreboard.',
    'list3': 'Hosts inter-university competitions and practices.',
    'list4': 'Open to the public during select hours.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'bahoshy_field.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Field',
    'location': LatLng(40.863883811300056, -73.88431932331652),
    'subText': 'Open field for sports and recreational use.',
    'list1': 'Ideal for informal sports and student gatherings.',
    'list2': 'Located centrally with easy access from residence halls.',
    'list3': 'Regularly used for intramural sports and events.',
    'list4': 'Surrounded by pathways and seating areas.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'field.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Bahoshy Softball Complex',
    'location': LatLng(40.86304908748162, -73.88356374252838),
    'subText': 'Specialized softball training and competition area.',
    'list1': 'Designed for softball practices and matches.',
    'list2': 'Complete with batting cages and equipment storage.',
    'list3': 'Frequently hosts visiting teams for matches.',
    'list4': 'Adjacent to other athletic facilities on campus.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'bahoshy_softball_complex.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Rose Hill Gymnasium',
    'location': LatLng(40.86192025165094, -73.88440081502361),
    'subText': 'Main indoor gym facility for various sports.',
    'list1': 'Hosts basketball, volleyball, and other indoor sports.',
    'list2': 'Open to students and faculty for recreational use.',
    'list3': 'Equipped with modern training and locker facilities.',
    'list4': 'Seating available for spectators during events.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'rose_hill_gymnasium.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'McShane Campus Center Back',
    'location': LatLng(40.86284963153381, -73.88385094998279),
    'subText': 'Back entrance to the McShane Campus Center.',
    'list1': 'Secondary entrance providing additional access.',
    'list2': 'Leads directly to dining and lounge areas.',
    'list3': 'Accessible by pathway and nearby parking.',
    'list4': 'Often less crowded than the main entrance.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'Street View 360_1.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Lombardi Memorial Center',
    'location': LatLng(40.862900051308, -73.88366946285079),
    'subText': 'Memorial center dedicated to Lombardi.',
    'list1': 'Features exhibits and historical displays.',
    'list2': 'Memorializes Lombardi’s contributions to the university.',
    'list3': 'Occasionally used for events and tours.',
    'list4': 'Located near other academic buildings.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'lombardi_memorial_center.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Walsh Training Center',
    'location': LatLng(40.86228100228768, -73.88272499491018),
    'subText': 'Athletic training facility for student athletes.',
    'list1': 'Features modern workout and conditioning equipment.',
    'list2': 'Used by varsity athletes for conditioning and rehab.',
    'list3': 'Access controlled, with trainers available on-site.',
    'list4': 'Conveniently located near athletic fields.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'walsh_training_center.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Jack Coffey Field',
    'location': LatLng(40.86147765821646, -73.88261187068268),
    'subText': 'Large stadium used for football and track events.',
    'list1': 'Home field for the university’s football team.',
    'list2': 'Equipped with a track around the field for running.',
    'list3': 'Hosts intercollegiate and intramural events.',
    'list4': 'Seating available for spectators during games.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'jack_coffey_field.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Xavier Way',
    'location': LatLng(40.86077176290269, -73.88184148720234),
    'subText': 'Pathway connecting various parts of campus.',
    'list1': 'Lined with trees, offering a scenic route.',
    'list2': 'Frequently used by students to navigate campus.',
    'list3': 'Nearby benches and shaded areas for relaxation.',
    'list4': 'Leads to athletic and academic buildings.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'xavier_way.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Fordham Store || Bookstore',
    'location': LatLng(40.85959805899672, -73.88272298718134),
    'subText': 'Campus store for books, apparel, and essentials.',
    'list1': 'Offers textbooks, university merchandise, and supplies.',
    'list2': 'Frequented by students for class materials.',
    'list3': 'Conveniently located near the main campus entrance.',
    'list4': 'Often has seasonal sales and exclusive items.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'fordham_store.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': "O'Hare Hall",
    'location': LatLng(40.859256309232265, -73.88277484476826),
    'subText': 'Residential hall with modern amenities.',
    'list1': 'Provides comfortable living spaces for students.',
    'list2': 'Equipped with study lounges and common areas.',
    'list3': 'Features dining options and student services.',
    'list4': 'Located centrally for easy campus access.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'ohare_hall.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Tierney Hall',
    'location': LatLng(40.85928992605681, -73.88348968026257),
    'subText': 'Residential hall with a focus on community living.',
    'list1': 'Popular residence with spacious rooms.',
    'list2': 'Includes laundry and study facilities.',
    'list3': 'Known for active community programs.',
    'list4': 'Located close to academic buildings.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'tierney_hall.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'RAM Van',
    'location': LatLng(40.8590798306726, -73.88227853215828),
    'subText': 'University shuttle service area.',
    'list1': 'Provides transport between campuses.',
    'list2': 'Available to students and staff for easy commuting.',
    'list3': 'Frequently operates between peak hours.',
    'list4': 'Accessible from various campus locations.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'ram_van.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Regional Parking Facility',
    'location': LatLng(40.85874927585338, -73.88180815161397),
    'subText': 'Parking facility for students and visitors.',
    'list1': 'Offers ample parking space for campus visitors.',
    'list2': 'Accessible from multiple campus entry points.',
    'list3': 'Provides short-term and long-term parking options.',
    'list4': 'Close to main campus buildings.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'parking_facility.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Communication Department',
    'location': LatLng(40.85841032410379, -73.88259706112997),
    'subText': 'Department focused on communication studies.',
    'list1': 'Houses faculty offices and classrooms.',
    'list2': 'Offers resources for media and communication studies.',
    'list3': 'Hosts guest lectures and special events.',
    'list4': 'Equipped with media labs and studios.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'communication_department.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Canisius Hall',
    'location': LatLng(40.8586204225088, -73.88274521203577),
    'subText': 'Academic building with lecture halls.',
    'list1': 'Home to several academic departments.',
    'list2': 'Includes large lecture halls and seminar rooms.',
    'list3': 'Frequented by students for various classes.',
    'list4': 'Located near the main campus pathway.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'canisius_hall.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Keating Hall',
    'location': LatLng(40.860569492650555, -73.88353242172421),
    'subText': 'Iconic campus building with historical significance.',
    'list1': 'Known for its gothic architecture and design.',
    'list2': 'Houses classrooms and administrative offices.',
    'list3': 'Popular location for university events.',
    'list4': 'Close to other major campus facilities.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'keating_hall.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': "Edward's Parade",
    'location': LatLng(40.86098966739332, -73.88524730060098),
    'subText': 'Expansive green space for relaxation and gatherings.',
    'list1': 'Ideal for outdoor events and university celebrations.',
    'list2': 'Frequently used by students for studying and recreation.',
    'list3': 'Scenic area with walking paths and benches.',
    'list4': 'Central location on campus with easy access.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'edwards_parade.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': "Edward's Parade",
    'location': LatLng(40.86135943400756, -73.88456579661496),
    'subText': 'Another section of the central campus green space.',
    'list1': 'Features shaded areas under large trees.',
    'list2': 'Commonly used for informal gatherings and picnics.',
    'list3': 'Pathways connect to nearby academic buildings.',
    'list4': 'Popular for student activities and leisure.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'edwards_parade_2.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'McShane Back',
    'location': LatLng(40.86284963153381, -73.88385094998279),
    'subText': 'Back entrance to McShane Center with seating areas.',
    'list1': 'Quiet area with benches for relaxing and studying.',
    'list2': 'Provides easy access to the McShane Center.',
    'list3': 'Nearby landscaped gardens and open green space.',
    'list4': 'Often used as a shortcut to other buildings.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'gymnasium_2.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Lombardi Memorial Center',
    'location': LatLng(40.862900051308, -73.88366946285079),
    'subText': 'Sports and recreation center for students.',
    'list1': 'Includes facilities for basketball and volleyball.',
    'list2': 'Equipped with fitness and training equipment.',
    'list3': 'Hosts sports events and fitness classes.',
    'list4': 'Popular destination for student athletes.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'lombardi_center.jpg',
  },
  {
    'image': 'assets/images/backgrounds/fordham.jpg',
    'name': 'Walsh Training Center',
    'location': LatLng(40.86228100228768, -73.88272499491018),
    'subText': 'Athletic training facility for advanced fitness.',
    'list1': 'Features weight rooms and cardio equipment.',
    'list2': 'Offers specialized training sessions for athletes.',
    'list3': 'Used for team practice and individual workouts.',
    'list4': 'Open to all students with gym memberships.',
    'status': 'Open from 9:00AM - 6:00PM',
    'panoramaImage': 'walsh_training_center.jpg',
  },

];



